### ISSUE TITLE
package.use.mask?

### ISSUE THREAD

**Issue by hanetzer** [trofi/overlay-selective-mask-in-gentoo#1]
Greets.

I was wondering if this technique could also be used for package.use.mask/unmask files
(for instance, media-libs/vulkan-loader is not available on x86, so app-emulation/wine*
has the vulkan use flag masked on non-amd64 profiles). I'm attempting it with [::abendbrot](https://github.com/stefan-gr/abendbrot),
but it does not seem to be working.

**Comment by trofi** [comment]
Yes, it should be the same. It should be masked around `profiles/arch/x86`

**Comment by hanetzer** [comment]
Can I do the mixin to profiles/arch/x86? I've never seen that done, and I don't think its a full
profile per se.

**Comment by trofi** [comment]
This overlay does similar thing: it masks a package for a few selinux targets by adding new non-leaf feature: `profiles/features/selinux` (it's not a profile on it's own) and applies to all profiles that use it.

I don't think gentoo allows you to modify profile hierarchy in master repository from overlay. Overlay can only override leaf profiles. That's what this repository does: it applies overrides on all profiles that need additional selinux mask injection.

**Comment by hanetzer** [comment]
gotcha, so you have to manually apply it to the `*/*/*/selinux` profiles manually, per-profile.
